name: provision-infra-for-the-iothub

on:
  push:
    branches: [main]
    paths:
      - "**/iothub_provision-infra.yml"

env:
  AZURE_RG: rg-we-iot
  TEMPLATE_PATH: ./RaspiConsumer/infra/rg-we-iot.bicep

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run validation
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group validate \
            --resource-group ${{ env.AZURE_RG }} \
            --template-file ${{ env.TEMPLATE_PATH }} \
            --parameters allowedIpV4CIDR=${{ secrets.DEV_MACHINE_IP }}

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name ${{ github.workflow }}_${{ github.run_number }} \
            --resource-group ${{ env.AZURE_RG }} \
            --template-file ${{ env.TEMPLATE_PATH }} \
            --parameters allowedIpV4CIDR=${{ secrets.DEV_MACHINE_IP }}
