name: build-and-deploy-the-raspi-consumer
on: [push]

env:
  AZURE_FA_NAME: fa-we-raspiconsumer
  FA_PACKAGE_PATH: '.'
  DOTNET_VERSION: 6.0.x

permissions:
      id-token: write
      contents: read
      
jobs:
  build-and-deploy:
      needs: []
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup .NET ${{ env.DOTNET_VERSION }} env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build
        shell: pwsh
        run: |
          pushd './${{ env.FA_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./publish
          popd
      
      - name: Deploy
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FA_NAME }}
          package: '${{ env.FA_PACKAGE_PATH }}/publish'