name: Provision required infrastructure for the Raspi Interface app

on:
  push:
    branches: [main]
    paths:
      - "**/RaspiInterface/infra/**"
      - "**/raspi-interface_provision-infra.yml"

env:
  AZURE_RG: rg-we-interface
  TEMPLATE_PATH: ./RaspiInterface/infra/rg-we-interface.bicep

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: './.github/actions/validate-infra'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group: ${{ env.AZURE_RG }}
          template-path: ${{ env.TEMPLATE_PATH }}

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: './.github/actions/deploy-infra'
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group: ${{ env.AZURE_RG }}
          template-path: ${{ env.TEMPLATE_PATH }}
          deployment-name: raspi-interface-infra-provisioning_${{ github.run_number }}
