name: Build & Deploy the Raspi Interface app
on:
  push:
    branches: [main]
    paths:
      - "**/RaspiInterface/**"
      - "**/raspi-interface_build-and-deploy.yml"

env:
  DOTNET_VERSION: 7.0.x
  BUILD_CONFIGURATION: Release
  APP_PATH: ./src/RaspiInterface/Server
  TESTS_PATH: ./test/RaspiInterface/**/bin/**/*.Tests.dll
  APP_PUBLISH_PATH: ${{ github.workspace}}/publish
  APP_SERVICE_NAME: app-we-interface

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ env.DOTNET_VERSION }} env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build '${{ env.APP_PATH }}'

      - name: Run integration tests
        run: dotnet test '${{ env.TESTS_PATH }}' --filter Category=Integration

  package:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ env.DOTNET_VERSION }} env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build '${{ env.APP_PATH }}' --configuration ${{ env.BUILD_CONFIGURATION }}
        
      - name: Publish
        run: dotnet publish '${{ env.APP_PATH }}' --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --output '${{ env.APP_PUBLISH_PATH }}'

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: raspiapp
          path: ${{ env.APP_PUBLISH_PATH }}
      
  deploy:
      needs: package
      runs-on: ubuntu-latest
      steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: raspiapp
          path: ${{ env.APP_PUBLISH_PATH }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.APP_SERVICE_NAME }}
          package: ${{ env.APP_PUBLISH_PATH }}
          resource-group-name: rg-we-interface
